export type Dialect = 'postgresql' | 'sqlite' | 'merged';

/** PostgreSQL 关键字（常用子集，够补全用；全部大写） */
const PG_KEYWORDS = `
SELECT FROM WHERE INSERT INTO VALUES UPDATE SET DELETE CREATE ALTER DROP TABLE VIEW INDEX
SCHEMA DATABASE TRUNCATE JOIN INNER LEFT RIGHT FULL OUTER CROSS ON USING GROUP ORDER BY
HAVING LIMIT OFFSET DISTINCT AS AND OR NOT NULL IS IN EXISTS BETWEEN LIKE ILIKE SIMILAR TO
CASE WHEN THEN ELSE END UNION INTERSECT EXCEPT ALL ANY SOME WITH RECURSIVE RETURNING CONFLICT
DO NOTHING PRIMARY KEY FOREIGN REFERENCES UNIQUE CHECK DEFAULT CONSTRAINT CASCADE RESTRICT
GRANT REVOKE BEGIN COMMIT ROLLBACK TRANSACTION SAVEPOINT RELEASE ANALYZE EXPLAIN VACUUM COPY
CAST ASC DESC NULLS FIRST LAST OVER PARTITION WINDOW FILTER WITHIN LATERAL MATERIALIZED
CONCURRENTLY IF TEMP TEMPORARY UNLOGGED GENERATED ALWAYS IDENTITY COLLATE ARRAY ROW ONLY
TABLESAMPLE FETCH NEXT ROWS NOWAIT FOR SHARE OF ESCAPE SIMILARITY INITIALLY DEFERRED IMMEDIATE
DOMAIN TYPE EXTENSION FUNCTION PROCEDURE TRIGGER LANGUAGE RETURNS IMMUTABLE STABLE VOLATILE
SECURITY DEFINER INVOKER OWNER RENAME ADD COLUMN REPLACE COMMENT PRIVILEGES OWNED BY SEQUENCE
SERIAL BIGSERIAL SMALLSERIAL INTEGER INT BIGINT SMALLINT NUMERIC DECIMAL REAL DOUBLE PRECISION
TEXT VARCHAR CHAR BOOLEAN BOOL UUID JSON JSONB BYTEA INET CIDR MACADDR MONEY XML TSVECTOR
POINT LINE BOX PATH POLYGON CIRCLE INTERVAL TIMESTAMP DATE TIME TIMESTAMPTZ NOTHING UNBOUNDED
PRECEDING FOLLOWING CURRENT EXCLUDE TIES OTHERS GROUPS CUBE ROLLUP GROUPING SETS ORDINALITY
BETWEEN SYMMETRIC ASYMMETRIC LEADING TRAILING BOTH PLACING VARIADIC STRICT PARALLEL SAFE
UNSAFE LEAKPROOF COST ROWS SUPPORT TRANSFORM CONCURRENT REFRESH INCREMENT MINVALUE MAXVALUE
CACHE CYCLE OWNED ATTACH DETACH PUBLICATION SUBSCRIPTION LOGGED UNLOGGED OVERRIDING SYSTEM
USER LOCALTIME LOCALTIMESTAMP
`;

/** SQLite 关键字（全部大写） */
const SQLITE_KEYWORDS = `
ABORT ACTION ADD AFTER ALL ALTER ALWAYS ANALYZE AND AS ASC ATTACH AUTOINCREMENT BEFORE BEGIN
BETWEEN BY CASCADE CASE CAST CHECK COLLATE COLUMN COMMIT CONFLICT CONSTRAINT CREATE CROSS
CURRENT CURRENT_DATE CURRENT_TIME CURRENT_TIMESTAMP DATABASE DEFAULT DEFERRABLE DEFERRED DELETE
DESC DETACH DISTINCT DO DROP EACH ELSE END ESCAPE EXCEPT EXCLUDE EXCLUSIVE EXISTS EXPLAIN FAIL
FILTER FIRST FOLLOWING FOR FOREIGN FROM FULL GENERATED GLOB GROUP GROUPS HAVING IF IGNORE
IMMEDIATE IN INDEX INDEXED INITIALLY INNER INSERT INSTEAD INTERSECT INTO IS ISNULL JOIN KEY
LAST LEFT LIKE LIMIT MATCH MATERIALIZED NATURAL NO NOT NOTHING NOTNULL NULL NULLS OF OFFSET ON
OR ORDER OTHERS OUTER OVER PARTITION PLAN PRAGMA PRECEDING PRIMARY QUERY RAISE RANGE RECURSIVE
REFERENCES REGEXP REINDEX RELEASE RENAME REPLACE RESTRICT RETURNING RIGHT ROLLBACK ROW ROWS
SAVEPOINT SELECT SET TABLE TEMP TEMPORARY THEN TIES TO TRANSACTION TRIGGER UNBOUNDED UNION
UNIQUE UPDATE USING VACUUM VALUES VIEW VIRTUAL WHEN WHERE WINDOW WITH WITHOUT
`;

/** PostgreSQL 常用函数（全部大写） */
const PG_FUNCTIONS = `
COUNT SUM AVG MIN MAX ABS CEIL CEILING FLOOR ROUND TRUNC MOD POWER SQRT EXP LN LOG RANDOM
NOW CURRENT_DATE CURRENT_TIME CURRENT_TIMESTAMP AGE DATE_TRUNC DATE_PART EXTRACT TO_CHAR TO_DATE
TO_NUMBER TO_TIMESTAMP MAKE_DATE MAKE_TIME MAKE_TIMESTAMP MAKE_INTERVAL JUSTIFY_DAYS
COALESCE NULLIF GREATEST LEAST LENGTH CHAR_LENGTH OCTET_LENGTH BIT_LENGTH UPPER LOWER INITCAP
TRIM LTRIM RTRIM LPAD RPAD REPLACE SUBSTRING SUBSTR POSITION STRPOS SPLIT_PART CONCAT CONCAT_WS
REPEAT REVERSE LEFT RIGHT MD5 SHA256 ENCODE DECODE GEN_RANDOM_UUID GEN_SALT CRYPT
ARRAY_AGG STRING_AGG ARRAY_LENGTH CARDINALITY UNNEST GENERATE_SERIES GENERATE_SUBSCRIPTS
JSON_AGG JSONB_AGG JSON_OBJECT_AGG JSONB_OBJECT_AGG JSON_BUILD_OBJECT JSONB_BUILD_OBJECT
JSONB_SET JSONB_INSERT JSONB_PATH_QUERY JSONB_PATH_QUERY_FIRST TO_JSON TO_JSONB JSONB_TYPEOF
ROW_NUMBER RANK DENSE_RANK PERCENT_RANK CUME_DIST NTILE LAG LEAD FIRST_VALUE LAST_VALUE NTH_VALUE
MODE PERCENTILE_CONT PERCENTILE_DISC STDDEV VARIANCE CORR COVAR_POP COVAR_SAMP REGR_SLOPE
REGEXP_REPLACE REGEXP_MATCH REGEXP_MATCHES REGEXP_SPLIT_TO_ARRAY REGEXP_SPLIT_TO_TABLE
FORMAT QUOTE_IDENT QUOTE_LITERAL QUOTE_NULLABLE NUM_NONNULLS NUM_NULLS PG_TYPEOF
VERSION CURRENT_SCHEMA CURRENT_DATABASE SESSION_USER CURRENT_USER TXID_CURRENT
SET_CONFIG CURRENT_SETTING PG_SLEEP CLOCK_TIMESTAMP STATEMENT_TIMESTAMP
`;

/** SQLite 常用函数（全部大写） */
const SQLITE_FUNCTIONS = `
COUNT SUM TOTAL AVG MIN MAX ABS ROUND RANDOM RANDOMBLOB ZEROBLOB LENGTH LOWER UPPER SUBSTR
SUBSTRING TRIM LTRIM RTRIM REPLACE INSTR HEX UNICODE CHAR PRINTF FORMAT QUOTE TYPEOF COALESCE
IFNULL NULLIF IIF DATE TIME DATETIME JULIANDAY STRFTIME UNIXEPOCH TIMEDIFF DATEADD CEIL CEILING
FLOOR POW POWER SQRT EXP LN LOG LOG2 LOG10 MOD SIGN GROUP_CONCAT JSON JSON_ARRAY JSON_OBJECT
JSON_EXTRACT JSON_INSERT JSON_REPLACE JSON_SET JSON_REMOVE JSON_TYPE JSON_VALID JSON_QUOTE
JSON_GROUP_ARRAY JSON_GROUP_OBJECT JSON_EACH JSON_TREE JSON_PATCH JSON_ARRAY_LENGTH
ROW_NUMBER RANK DENSE_RANK PERCENT_RANK CUME_DIST NTILE LAG LEAD FIRST_VALUE LAST_VALUE NTH_VALUE
LAST_INSERT_ROWID CHANGES TOTAL_CHANGES SQLITE_VERSION SQLITE_SOURCE_ID LIKELY UNLIKELY
LOAD_EXTENSION SQLITE_COMPILEOPTION_GET SQLITE_COMPILEOPTION_USED
`;

function dedupe(raw: string): string[] {
  const seen = new Set<string>();
  const out: string[] = [];
  for (const w of raw.toUpperCase().split(/\s+/)) {
    if (w && !seen.has(w)) {
      seen.add(w);
      out.push(w);
    }
  }
  return out;
}

const PG_KW = dedupe(PG_KEYWORDS);
const SQLITE_KW = dedupe(SQLITE_KEYWORDS);
const PG_FN = dedupe(PG_FUNCTIONS);
const SQLITE_FN = dedupe(SQLITE_FUNCTIONS);
const MERGED_KW = (() => {
  const seen = new Set(PG_KW);
  return [...PG_KW, ...SQLITE_KW.filter((w) => !seen.has(w))];
})();
const MERGED_FN = (() => {
  const seen = new Set(PG_FN);
  return [...PG_FN, ...SQLITE_FN.filter((w) => !seen.has(w))];
})();

export function keywords(dialect: Dialect): string[] {
  if (dialect === 'sqlite') return SQLITE_KW;
  if (dialect === 'merged') return MERGED_KW;
  return PG_KW;
}

export function functions(dialect: Dialect): string[] {
  if (dialect === 'sqlite') return SQLITE_FN;
  if (dialect === 'merged') return MERGED_FN;
  return PG_FN;
}
